name: CodingForYou.net
on: push
jobs:
  upload-to-server:
    runs-on: ubuntu-latest
    uses: appleboy/ssh-action@master
    with:
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.KEY }}
      port: ${{ secrets.PORT }}
      script: |
        cd web-server/CodingForYou.net
        npm run deploy
